spring:
  application:
    name: transfer-api
  datasource:
    url: jdbc:h2:mem:transactionbd  # Base de datos en memoria
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

BASE_URL: ${URL_API:http://localhost:8081/api}

server:
  port: 8082
